function dfdx = computeA(x1,x2)
%computeA
%    DFDX = computeA(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Jan-2025 10:53:08

dfdx = reshape([x2-1.0,x2.*(-4.0./3.0),x1,x1.*(-4.0./3.0)+2.0./3.0],[2,2]);
end
