function dfdx = computeA(x1,x2)
%computeA
%    DFDX = computeA(X1,X2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    04-Nov-2024 19:34:51

dfdx = reshape([x2-1.0,x2.*(-4.0./3.0),x1,x1.*(-4.0./3.0)+2.0./3.0],[2,2]);
end
